FROM node:20.17.0-alpine

WORKDIR /client

# COPY package.json .
# RUN npm install --legacy-peer-deps
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps
COPY . .
CMD [ "npm", "run", "dev" ]
